require('dotenv').config();

export default {
	ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
	REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
	GENERATE_ACCESS_TOKEN_EXPIRES_IN: '1d',
	GENERATE_REFRESH_TOKEN_EXPIRES_IN: '1M'
};
